name: pre-commit checks

on: [push]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@master
        with:
          python-version: 3.12

      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files
